# Generated by Django 4.2.6 on 2023-10-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_description_alter_car_features_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=200),
        ),
    ]
